version: '3.5'
services:
  vector_extractor:
    image: glemoine/dias_numba_py:latest
    volumes:
            - /home/eouser/jrc-dias/scripts:/usr/src/app
            - /eodata:/eodata
            - /1/DIAS:/1/DIAS
    networks:
      - overnet
    deploy:
      replicas: 4
    command: python factoredWindowedExtraction.py c6 20

networks:
  overnet:
