version: '3.5'
services:
  vector_extractor:
    image: glemoine62/dias_numba_py:latest
    volumes:
            - /home/eouser/cbm/extraction:/usr/src/app
            - /eodata:/eodata
            - /1/DIAS:/1/DIAS
    deploy:
      replicas: 3
    command: python factoredWindowedExtraction.py bs 10

